/**
 * GENERATED by scripts/gen-changelog.mjs from CHANGELOG.md. Do not edit by
 * hand — edit CHANGELOG.md and re-run the script.
 *
 * @module changelog
 */
export const CHANGELOG = [
  {
    version: 'Unreleased',
    date: null,
    items: [
      {
        tag: 'Added',
        text: 'Ansible Automation Platform 2.6 sample (~40k packages), a large-SBOM stress test, with a VEX overlay converted from Red Hat CSAF.'
      },
      {
        tag: 'Improved',
        text: 'Impact view shows package versions, so different builds of the same package are distinguishable.'
      },
      {
        tag: 'Improved',
        text: 'Opening an element deep in a large list jumps straight to it and loads more as you scroll up or down, instead of rendering every row above it.'
      }
    ]
  },
  {
    version: '0.0.5',
    date: '2026-07-05',
    items: [
      {
        tag: 'Added',
        text: 'Shareable links tracking the current view and selected element.'
      },
      {
        tag: 'Added',
        text: 'PackageURL identifiers link out to deps.dev.'
      },
      {
        tag: 'Added',
        text: 'Impact view: trace provenance and blast radius, with risk rankings.'
      },
      {
        tag: 'Added',
        text: 'Security view surfacing CVSS, EPSS, and known-exploited signals.'
      },
      {
        tag: 'Added',
        text: 'Statistics view with completeness score and category breakdowns.'
      },
      {
        tag: 'Added',
        text: 'Dedicated Agents view.'
      },
      {
        tag: 'Added',
        text: 'CreatedBy/performedBy provenance edges, hidden by default.'
      },
      {
        tag: 'Changed',
        text: 'Simplified the dashboard and sidebar; empty views stay hidden.'
      },
      {
        tag: 'Changed',
        text: 'Migrated the build to Vite.'
      },
      {
        tag: 'Fixed',
        text: 'UI cut off on mobile browsers.'
      }
    ]
  },
  {
    version: '0.0.4',
    date: '2026-07-04',
    items: [
      {
        tag: 'Added',
        text: 'SPDX ExternalMap support, with placeholder nodes for external elements.'
      },
      {
        tag: 'Added',
        text: 'Experimental Zephyr SPDX 3.1 sample.'
      },
      {
        tag: 'Added',
        text: 'SPDX 3.1 Hardware profile support.'
      },
      {
        tag: 'Added',
        text: 'SPDX 3.1 Functional Safety profile support, with a dedicated Requirements view.'
      },
      {
        tag: 'Fixed',
        text: 'Build configs view showing up with nothing to show.'
      }
    ]
  },
  {
    version: '0.0.3',
    date: '2026-07-03',
    items: [
      {
        tag: 'Improved',
        text: 'Package and file lists now load incrementally on scroll.'
      },
      {
        tag: 'Added',
        text: 'AI model and dataset views, with a matching sample SBOM.'
      },
      {
        tag: 'Added',
        text: 'Global search across all elements.'
      },
      {
        tag: 'Added',
        text: 'CycloneDX to SPDX 3 converter.'
      },
      {
        tag: 'Added',
        text: 'Raw JSON-LD view with syntax highlighting.'
      },
      {
        tag: 'Added',
        text: 'Trivy vulnerability scan sample; vulnerability/VEX filters now auto-enable when a scan has findings.'
      }
    ]
  },
  {
    version: '0.0.2',
    date: '2026-07-03',
    items: [
      {
        tag: 'Added',
        text: 'Sample SBOMs for Vue.js, Jenkins, Android, and Kubernetes.'
      },
      {
        tag: 'Added',
        text: 'CycloneDX property display, plus dynamic link, optional component, and hasVariant relationship types.'
      },
      {
        tag: 'Improved',
        text: 'Graph rendering performance for large SBOMs, via node caching and a faster draw path.'
      },
      {
        tag: 'Improved',
        text: 'File list rendering, via memoization.'
      }
    ]
  },
  {
    version: '0.0.1',
    date: '2026-07-02',
    items: [
      {
        tag: 'Added',
        text: 'Initial release. Interactive relationship graph for SPDX 3 SBOMs, color-coded by element type.'
      },
      {
        tag: 'Added',
        text: 'Sample SBOMs for Linux, Windows, Yocto, Zephyr, and a Docker container image.'
      }
    ]
  }
];
