/**
 * GENERATED by scripts/gen-changelog.mjs from CHANGELOG.md. Do not edit by
 * hand — edit CHANGELOG.md and re-run the script.
 *
 * @module changelog
 */
export const CHANGELOG = [
  {
    version: 'Unreleased',
    date: null,
    items: [
      {
        tag: 'Changed',
        text: 'migrated the build to Vite; reorganized source into modules and view partials.'
      },
      {
        tag: 'Added',
        text: 'dedicated Agents view.'
      },
      {
        tag: 'Added',
        text: 'createdBy/performedBy provenance edges in the graph, hidden by default.'
      },
      {
        tag: 'Fixed',
        text: 'UI cut off on mobile browsers.'
      }
    ]
  },
  {
    version: '0.0.4',
    date: '2026-07-04',
    items: [
      {
        tag: 'Added',
        text: 'SPDX 3.1 Hardware profile support.'
      },
      {
        tag: 'Added',
        text: 'SPDX 3.1 Functional Safety profile support, with a dedicated Requirements view.'
      },
      {
        tag: 'Added',
        text: 'experimental Zephyr SPDX 3.1 sample.'
      },
      {
        tag: 'Fixed',
        text: 'build configs view showing up with nothing to show.'
      },
      {
        tag: 'Fixed',
        text: 'requirement filters not resetting between requirements.'
      }
    ]
  },
  {
    version: '0.0.3',
    date: '2026-07-03',
    items: [
      {
        tag: 'Added',
        text: 'CycloneDX to SPDX 3 converter.'
      },
      {
        tag: 'Added',
        text: 'Raw JSON-LD view with syntax highlighting.'
      },
      {
        tag: 'Added',
        text: 'SPDX ExternalMap support, with placeholder nodes for external elements.'
      },
      {
        tag: 'Improved',
        text: 'vulnerability/VEX filters auto-enable when a scan has findings.'
      },
      {
        tag: 'Added',
        text: 'Trivy vulnerability scan sample.'
      }
    ]
  },
  {
    version: '0.0.2',
    date: '2026-07-03',
    items: [
      {
        tag: 'Improved',
        text: 'graph rendering performance for large SBOMs, via node caching and a faster draw path.'
      },
      {
        tag: 'Improved',
        text: 'package and file lists now load incrementally on scroll.'
      },
      {
        tag: 'Added',
        text: 'AI model and dataset views, with a matching sample SBOM.'
      },
      {
        tag: 'Added',
        text: 'global search across all elements.'
      }
    ]
  },
  {
    version: '0.0.1',
    date: '2026-07-02',
    items: [
      {
        tag: 'Added',
        text: 'interactive relationship graph for SPDX 3 SBOMs, color-coded by element type.'
      },
      {
        tag: 'Added',
        text: 'sample SBOMs for Linux, Windows, Yocto, Zephyr, Docker, Vue.js, Jenkins, Android, and Kubernetes.'
      },
      {
        tag: 'Added',
        text: 'CycloneDX property display, plus dynamic link, optional component, and hasVariant relationship types.'
      }
    ]
  }
];
